"""
SOSAI -- Review Layer
Fetch et evalue les papers sous review dans le repo B.
"""

from datetime import datetime
from pathlib import Path

try:
    import requests
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False


def _headers(token: str) -> dict:
    return {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
    }


def fetch_papers_for_review(repo_url: str, github_token: str, status: str = "under_review") -> list:
    """
    Fetche tous les papers d'un dossier du repo B.
    """
    if not HAS_REQUESTS:
        return []

    parts = repo_url.rstrip("/").replace("https://github.com/", "").split("/")
    if len(parts) < 2:
        return []
    owner, repo = parts[0], parts[1]

    api_url = f"https://api.github.com/repos/{owner}/{repo}/contents/{status}"
    resp = requests.get(api_url, headers=_headers(github_token), timeout=15)
    if not resp.ok:
        return []

    files = resp.json()
    papers = []
    for f in files:
        if f.get("name", "").endswith(".md"):
            content_resp = requests.get(f["download_url"], timeout=15)
            if content_resp.ok:
                papers.append({
                    "id": f["name"].replace(".md", ""),
                    "filename": f["name"],
                    "url": f.get("html_url", ""),
                    "content": content_resp.text,
                })
    return papers


def format_review(
    paper_id: str,
    decision: str,
    score: float,
    strengths: list,
    required_changes: list,
    blocking_issues: list,
    comments: str,
    reviewer_model: str,
    reviewer_provider: str,
    reviewer_tier: int,
) -> str:
    """
    Formate un review en markdown pour soumission comme commentaire PR.
    """
    return f"""## SOSAI Review — {paper_id}

**Reviewer:** {reviewer_model} ({reviewer_provider}) — Tier {reviewer_tier}
**Score:** {score}/100
**Decision:** `{decision}`
**Date:** {datetime.now().isoformat()}

### Strengths
{chr(10).join(f'- {s}' for s in strengths)}

### Required Changes
{chr(10).join(f'- {c}' for c in required_changes) if required_changes else '- None'}

### Blocking Issues
{chr(10).join(f'- {i}' for i in blocking_issues) if blocking_issues else '- None'}

### Comments
{comments}

---
*Review generated by SOSAI v0.1.0*
"""


def post_review_comment(
    repo_url: str,
    github_token: str,
    pr_number: int,
    review_content: str,
) -> dict:
    """
    Poste le review comme commentaire sur la PR GitHub.
    """
    if not HAS_REQUESTS:
        return {"success": False, "error": "requests non installe"}

    parts = repo_url.rstrip("/").replace("https://github.com/", "").split("/")
    owner, repo = parts[0], parts[1]
    api_url = f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments"

    resp = requests.post(
        api_url,
        headers={**_headers(github_token), "Content-Type": "application/json"},
        json={"body": review_content},
        timeout=15,
    )
    if resp.status_code == 201:
        return {"success": True, "url": resp.json().get("html_url", "")}
    return {"success": False, "error": resp.text[:100]}
